### PR TITLE
Edit the date of Discord Partner & Early Verified Bot Developer changes.

### PR DESCRIPTION
**Pull request by Abu-Maher**

### CODE REVIEW

**Review by mezotv — COMMENTED** [review]
Do you got any official support articles or resources that can orove this information as correct?

**Comment by Abu-Maher** [comment]
I sent it in ur DMs on Discord.

**Comment by mezotv** [comment]
> I sent it in ur DMs on Discord.

I need actual information and resources not just a screenshot in arabic.

**Comment by Abu-Maher** [comment]
For Discord Partner (Partner Server Owner) you can check the way back machine:
this is the full list:
https://web.archive.org/web/20201001000000*/https://discord.com/partners
this snapshot was in 27 August 2020 which mean its changed:
https://web.archive.org/web/20200827223931/https://discord.com/partners
and this snapshot was in 20 August 2020:
https://web.archive.org/web/20200820064314/https://discord.com/partners

And for (Early) Verified Bot Developer I cannot find another clue, just the old screenshot.

**Comment by mezotv** [comment]
Just checked a few resources and they dont seem to match this pr. Thanks though!

**Pull request closed without merging**
